### ISSUE TITLE
[Bug]: Tacz interacting function not working properly with modded blocks/entities

### ISSUE THREAD

**Issue by The-idk-notdot** [MCModderAnchor/TACZ#227]
### I have confirmed that ...

- [x] tacz is up to date
- [X] unable to reproduce without tacz

### Minecraft and modloader version

1.20.1 ; forge 47.3.0

### tac version

1.20.1-1.0.2

### Related Mods

```raw
Tacz
Any mod that is adding blocks with graphical ui or entities with interacting function, like quark.
```

### Description

The tacz interacting with a gun mechanic is not working with modded blocks with graphical ui/entities. In this video, i can't get acess to quark's deepslate furnace:

https://github.com/user-attachments/assets/873e65de-879d-49fa-aedd-e2bd5ebd541e

### Step to reproduce

1. Install tacz and some mods that have blocks with graphical ui.
2. Join any world.
3. Try to interact vanilla and modded blocks/entities.

**Comment by xjqsh** [comment]
blocks/entity the interact key can interact with should be defined by tag manually via **datapack**. Since we don't know what blocks or entities other mods have, the blocks or entities from other mods are not listed by default. 
ref https://github.com/MCModderAnchor/TACZ/tree/1.20.1/src/main/resources/data/tacz/tags/blocks/interact_key
just add the block id to this tag
