### ISSUE TITLE
建议修改为不会穿透通用机械的护盾

### ISSUE THREAD

**Issue by ReallyChooseC** [MCModderAnchor/TACZ#52]
伤害能够穿透[Mek](https://www.mcmod.cn/class/187.html)的求生者套装

我认为这和原版护甲穿透的描述不符

一个生存末期的护甲，不应该被中期甚至初期就能做的武器穿透

能否修改为不会穿透Mek的护甲?(或者应该叫护盾？)

**Comment by ReallyChooseC** [comment]
额，是求生者套装吗？
还是叫MekaSuit套装

**Comment by ReallyChooseC** [comment]
不小心点错了（

**Comment by 3TUSK** [comment]
Note for developers:

~~mekanism/Mekanism#7997 allows 3rd party mods/packs to define a damage absorption ratio for each damage type. Should be fairly simple to add one JSON here. ~~

~~The real issue is the default ratio - what kind of balance do you wish to have by default?~~

Ignore what i said above. 
The said PR is only available for Mekansim **on NeoForge** because that function relies on NeoForge. And TaC:Z is not on NeoForge at this moment.

Use config file instead. There is a `damageReductionRatio` in `config/Mekanism/gear.toml` which allows custom damage absorption ratio by damage type.

**Comment by ReallyChooseC** [comment]
> Note for developers:
> 
> [mekanism/Mekanism#7997](https://github.com/mekanism/Mekanism/pull/7997) allows 3rd party mods/packs to define a damage absorption ratio for each damage type. Should be fairly simple to add one JSON here.
> 
> The real issue is the default ratio - what kind of balance do you wish to have by default?

What is the default ratio roughly on the general type of injury?
What should I do if I want to go ahead and add a JSON now?

**Comment by 286799714** [comment]
> Note for developers:
> 
> [mekanism/Mekanism#7997](https://github.com/mekanism/Mekanism/pull/7997) allows 3rd party mods/packs to define a damage absorption ratio for each damage type. Should be fairly simple to add one JSON here.
> 
> The real issue is the default ratio - what kind of balance do you wish to have by default?

Based on the issue description, I think we should set a default value that is closer to 1.

**Comment by 3TUSK** [comment]
Quick update.

Upon further check, it appears that, if you are using Mekansim on 1.20.1 + Forge, there is only one way to change damage absorption ratio: config file. 
There is a `damageReductionRatio` in `config/Mekanism/gear.toml`; it allows custom damage absorption ratio by damage type.

That json thing requires NeoForge. Apologize for the confusion & inconvenience.

**Comment by ReallyChooseC** [comment]
Will this issue ever be resolved?

**Comment by TartaricAcid** [comment]
Nope
